<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFormDeisTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    #patricio.aguilera@minsal.cl
    public function up () {
        Schema::create('form_deis', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('estado_registro')->nullable(true);#Para prevenir doble modificacion
            $table->string('nombres_madre')->nullable(true);
            $table->string('primer_apellido_madre')->nullable(true);
            $table->string('segundo_apellido_madre')->nullable(true);
            $table->timestamp('fecha_nacimiento_madre')->nullable(true);
            $table->integer('n_correlativo_interno')->nullable(true);
            $table->integer('id_region')->nullable(true);
            $table->integer('id_servicio_salud')->nullable(true);
            $table->integer('run_madre')->nullable(true);
            $table->string('digito_verificador')->nullable(true);
            $table->integer('edad')->nullable(true);
            $table->string('nacionalidad')->nullable(true);
            $table->string('id_pais')->nullable(true);
            $table->string('pueblos_indigenas')->nullable(true);
            $table->string('estado_civil')->nullable(true);
            $table->string('tipo_de_convivencia')->nullable(true);
            $table->string('escolaridad')->nullable(true);
            $table->integer('anos_estudio')->nullable(true);
            $table->string('residencia_gestante')->nullable(true);
            $table->integer('nacidos_vivos_previos_embarazo')->nullable(true);
            $table->integer('nacidos_muertos_previos_embarazo')->nullable(true);
            $table->integer('abortos_previos_embarazo')->nullable(true);
            $table->string('sifilis_previa_embarazo')->nullable(true);
            $table->integer('ano_sifilis_previa_embarazo')->nullable(true);
            $table->string('otra_its_previa_embarazo')->nullable(true);
            $table->string('vih_conocido_previa_embarazo')->nullable(true);
            $table->timestamp('fecha_confirmacion_isp_vih_responde_si')->nullable(true);
            $table->string('adicciones')->nullable(true);
            $table->timestamp('fecha_ingreso_control_prenatal_embarazo')->nullable(true);
            $table->string('embarazo_con_control_parental')->nullable(true);
            $table->integer('edad_gestacional_ingreso_control_embarazo')->nullable(true);
            $table->string('lugar_control_prenatal')->nullable(true);
            $table->string('lugar_control_prenatal_otro')->nullable(true);
            $table->integer('codigo_establecimiento_control_prenatal_embarazo')->nullable(true);
            $table->timestamp('fecha_1_vdrl_embarazo')->nullable(true);
            $table->string('resultado_1_vdrl_embarazo')->nullable(true);
            $table->string('resultado_dilucion_1_vdrl_embarazo')->nullable(true);
            $table->string('eg_1_dvrl_embarazo')->nullable(true);
            $table->timestamp('fecha_2_vdrl_embarazo')->nullable(true);
            $table->string('resultado_2_vdrl_embarazo')->nullable(true);
            $table->string('resultado_dilucion_2_vdrl_embarazo')->nullable(true);
            $table->integer('eg_2_dvrl_embarazo')->nullable(true);
            $table->timestamp('fecha_3_vdrl_embarazo')->nullable(true);
            $table->string('resultado_3_vdrl_embarazo')->nullable(true);
            $table->string('resultado_dilucion_3_vdrl_embarazo')->nullable(true);
            $table->integer('eg_3_dvrl_embarazo')->nullable(true);
            $table->timestamp('fecha_examen_treponemico')->nullable(true);
            $table->string('resultado_treponemico')->nullable(true);
            $table->string('diagnostico_sifilis_embarazo')->nullable(true);
            $table->string('tratamiento_sifilis_farmaco')->nullable(true);
            $table->string('tratamiento_sifilis_dosis')->nullable(true);
            $table->string('tratamiento_sifilis_frecuencia')->nullable(true);
            $table->string('acepta_rechaza_toma_examen_vih')->nullable(true);
            $table->timestamp('fecha_1_examen_vih_embarazo')->nullable(true);
            $table->string('resultado_1_examen_vih_embarazo')->nullable(true);
            $table->integer('eg_1_examen_vih')->nullable(true);
            $table->timestamp('fecha_2_examen_vih_embarazo')->nullable(true);
            $table->string('resultado_2_examen_vih_embarazo')->nullable(true);
            $table->integer('eg_2_examen_vih')->nullable(true);
            $table->timestamp('fecha_resultado_final_isp_examen_vih')->nullable(true);
            $table->string('resultado_final_isp_examen_vih')->nullable(true);
            $table->string('derivada_a_especialidades_embarazo')->nullable(true);
            $table->timestamp('fecha_ingreso_unacess')->nullable(true);
            $table->timestamp('fecha_ingreso_control_unidad_alto_riesgo')->nullable(true);
            $table->timestamp('fecha_ingreso_control_centro_atencion_vih')->nullable(true);
            $table->timestamp('fecha_ingreso_control_otras_especialidades')->nullable(true);
            $table->string('fecha_ingreso_control_otras_especialidades_otro')->nullable(true);
            $table->string('terapia_antiretroviral_farmaco_1')->nullable(true);
            $table->timestamp('fecha_inicio_tar_farmaco_1')->nullable(true);
            $table->string('terapia_antiretroviral_tar_farmaco_2')->nullable(true);
            $table->timestamp('fecha_inicio_tar_farmaco_2')->nullable(true);
            $table->string('terapia_antiretroviral_tar_farmaco_3')->nullable(true);
            $table->timestamp('fecha_inicio_tar_farmaco_3')->nullable(true);
            $table->integer('numero_cd4_ingreso_control_prenatal')->nullable(true);
            $table->timestamp('fecha_examen_linfocitos_cd4_ingreso_control_prenatal')->nullable(true);
            $table->integer('carga_viral_numero_copia_ingreso_control_prenatal')->nullable(true);
            $table->timestamp('fecha_examen_carga_viral_control_prenatal')->nullable(true);
            $table->integer('numero_carga_viral_control_prenatal')->nullable(true);
            $table->integer('numero_contactos_sexuales_declarados')->nullable(true);
            $table->integer('numero_contactos_sexuales_estudiados')->nullable(true);
            $table->timestamp('carga_viral_numero_copia_semana_34')->nullable(true);
            $table->timestamp('fecha_examen_carga_viral_semana_34')->nullable(true);
            $table->integer('numero_contactos_sexuales_tratados')->nullable(true);
            $table->string('lugar_atencion_parto')->nullable(true);
            $table->integer('codigo_establecimiento')->nullable(true);
            $table->string('nombre_establecimiento_sin_codigo')->nullable(true);
            $table->timestamp('fecha_parto')->nullable(true);
            $table->timestamp('hora_parto')->nullable(true);
            $table->string('tipo_parto')->nullable(true);
            $table->string('via_parto')->nullable(true);
            $table->string('resultado_vdrl_parto')->nullable(true);
            $table->string('resultado_dilucion_vdrl_parto')->nullable(true);
            $table->string('resultado_examen_treponemico_parto')->nullable(true);
            $table->string('tratamiento_sifilis_parto')->nullable(true);
            $table->string('resultado_examen_vih_parto')->nullable(true);
            $table->string('tratamiento_retroviral_parto')->nullable(true);
            $table->integer('peso_mujer_parto')->nullable(true);
            $table->string('nombre_farmaco_1_vih')->nullable(true);
            $table->string('dosis_farmaco_1_vih')->nullable(true);
            $table->timestamp('fecha_inicio_farmaco_1_vih')->nullable(true);
            $table->timestamp('hora_inicio_farmaco_1_vih')->nullable(true);
            $table->string('nombre_farmaco_2_vih')->nullable(true);
            $table->string('dosis_farmaco_2_vih')->nullable(true);
            $table->timestamp('fecha_inicio_farmaco_2_vih')->nullable(true);
            $table->timestamp('hora_inicio_farmaco_2_vih')->nullable(true);
            $table->string('nombre_farmaco_suspencion_lactancia')->nullable(true);
            $table->timestamp('fecha_administracion_farmaco_suspencion_lactancia')->nullable(true);
            $table->string('estado_recien_nacido')->nullable(true);
            $table->integer('eg_pediatrica')->nullable(true);
            $table->string('sexo_recien_nacido')->nullable(true);
            $table->integer('peso_recien_nacido')->nullable(true);
            $table->string('estado_clinico_recien_nacido')->nullable(true);
            $table->integer('run_recien_nacido')->nullable(true);
            $table->string('digito_verificador_recien_nacido')->nullable(true);
            $table->string('codigo_recien_nacido')->nullable(true);
            $table->timestamp('fecha_examen_vdrl_periferico_recien_nacido')->nullable(true);
            $table->string('resultado_vdrl_periferico_recien_nacido')->nullable(true);
            $table->string('titulacion_vdrl_periferico_recien_nacido')->nullable(true);
            $table->integer('fecha_examen_vdrl_liq_cefalo_recien_nacido')->nullable(true);
            $table->string('resultado_vdrl_liq_cefalo_recien_nacido')->nullable(true);
            $table->string('titulacion_vdrl_liq_cefalo_recien_nacido')->nullable(true);
            $table->string('resultado_radiografia_huesos_largos')->nullable(true);
            $table->string('resultado_citoquimico_liq_cefalo_raquideo')->nullable(true);
            $table->string('resultado_estudio_placentario')->nullable(true);
            $table->string('tratamiento_recien_nacido_farmaco')->nullable(true);
            $table->string('tratamiento_recien_nacido_dosis')->nullable(true);
            $table->integer('tratamiento_recien_nacido_frecuencia')->nullable(true);
            $table->string('sustituto_leche_materna')->nullable(true);
            $table->timestamp('fecha_inicio_sustituto_leche_materna')->nullable(true);
            $table->timestamp('hora_inicio_sustituto_leche_materna')->nullable(true);
            $table->string('entrega_sustituto_leche_materna_al_alta')->nullable(true);
            $table->string('nombre_farmaco_1_vih_recien_nacido')->nullable(true);
            $table->string('dosis_farmaco_1_vih_recien_nacido')->nullable(true);
            $table->timestamp('fecha_inicio_farmaco_1_vih_recien_nacido')->nullable(true);
            $table->timestamp('hora_inicio_farmaco_1_vih_recien_nacido')->nullable(true);
            $table->string('nombre_farmaco_2_vih_recien_nacido')->nullable(true);
            $table->string('dosis_farmaco_2_vih_recien_nacido')->nullable(true);
            $table->timestamp('fecha_inicio_farmaco_2_vih_recien_nacido')->nullable(true);
            $table->timestamp('hora_inicio_farmaco_2_vih_recien_nacido')->nullable(true);
            $table->timestamp('fecha_1_examen_pcr_recien_nacido')->nullable(true);
            $table->string('resultado_1_examen_pcr_recien_nacido')->nullable(true);
            $table->timestamp('fecha_2_examen_pcr_recien_nacido')->nullable(true);
            $table->string('resultado_2_examen_pcr_recien_nacido')->nullable(true);
            $table->timestamp('fecha_3_examen_pcr_recien_nacido')->nullable(true);
            $table->string('resultado_3_examen_pcr_recien_nacido')->nullable(true);
            $table->string('diagnostico_final_vih_isp_recien_nacido')->nullable(true);
            $table->timestamp('fecha_test_elisa_18_meses')->nullable(true);
            $table->string('resultado_test_elisa_18_meses')->nullable(true);
            $table->timestamp('fecha_examen_treponemico_recien_nacido')->nullable(true);
            $table->string('derivacion_recien_nacido_a_seguimiento')->nullable(true);
            $table->string('lugar_derivacion_recien_nacido_a_seguimiento')->nullable(true);
            $table->timestamp('fecha_ingreso_control_recien_nacido_post_nacimiento')->nullable(true);
            $table->string('diagnostico_final_sifilis_recien_nacido')->nullable(true);
            $table->string('estado_seguimiento_mes')->nullable(true);
            $table->string('estado_seguimiento_3_meses')->nullable(true);
            $table->string('estado_seguimiento_6_meses')->nullable(true);
            $table->string('estado_seguimiento_12_meses')->nullable(true);
            $table->string('estado_seguimiento_18_meses')->nullable(true);

            $table->string('mujer_continua_tratamiento_antiretroviral')->nullable(true);
            $table->timestamp('fecha_ultima_regla')->nullable(true);
            $table->string('pareja_vih_positivo')->nullable(true);
            $table->timestamp('fecha_administracion_1_dosis_penicilina_gestante')->nullable(true);
            $table->timestamp('fecha_administracion_ult_dosis_penicilina_gestante')->nullable(true);


            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down () {
        Schema::drop('form_deis');
    }
}
